blank_issues_enabled: false
contact_links:
  - name: Azure User Voice for Feature Requests
    url: https://feedback.azure.com/forums/934536-azure-communication-services
    about: Please submit feature requests here.
  - name: Microsoft Q&A for Questions
    url: https://docs.microsoft.com/en-us/answers/topics/azure-communication-services.html
    about: Please ask questions here.
  - name: Support & Help Options
    url: https://docs.microsoft.com/en-gb/azure/communication-services/support
    about: For more information on our support & help options.
